# 8"""8                              eeeee  eeee 
# 8   8  eeee eeeee eeeee  eeeee     8   8     8 
# 82ee8e 8      8   8   8  8  82     82ee8     8 
# 82   8 82ee   82  8eee8e 8   8    82   82 eee8 
# 82   8 82     82  82   8 8   8    82   82 82    
# 82   8 82ee   82  82   8 82ee8    82eee82 82ee 
#                                                

[colors-dark]
foreground=f6dcac
background=00172e
alpha=0.888
selection-foreground=00172e
selection-background=faa968

cursor=00172e f6dcac

regular0=00172e
regular1=f85525
regular2=028391
regular3=e97b3c
regular4=faa968
regular5=3f8f8a
regular6=8cbfb8
regular7=f6dcac

bright0=57898a
bright1=f97751
bright2=35a2a7
bright3=ed9563
bright4=fbb986
bright5=65a5a1
bright6=a3ccc6
bright7=f6dcac

#  ______   __       ______                                       
# /_____/\ /_/\     /_____/\                                      
# \:::_ \ \\:\ \    \:::_ \ \                                     
#  \:\ \ \ \\:\ \    \:\ \ \ \                                    
#   \:\ \ \ \\:\ \____\:\ \ \ \                                   
#    \:\_\ \ \\:\/___/\\:\/.:| |                                  
#  ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
# /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
# \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#   /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#   \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#    \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#     \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#                                                                 
